### ISSUE TITLE
Should we maintain keychain or not?

### ISSUE THREAD

**Issue by pacoorozco** [gphotosuploader/gphotos-uploader-cli#86] opened 2019-07-12 08:14 UTC
Hi guys!

I've opened this issue to discuss if we should remove keychain integration to store the Google Photos token, and store it in LevelDB instead. 

Historically `gphotos-uploader-cli` used `gnome-keyring` to store this token in an efficient and secure way. @nmrshll decided to do it this way (I'm guessing) because he handn't any other DB available. But now we can use the LevelDB database (needed for tracking uploaded items) to store the token.

**PROS**:
- Easy to implement, we can remove `github.com/99designs/keyring` dependency.
- Seamless usage. Users don't need any keyring (kwallet, gnome-keyring).
- Headless / Docker friendly. It make easier to be used in a docker.

**CONS**:
- Less secure, the token will not be encrypted on LevelDB.

What do you think? Should we remove keychain integration?

**Comment by rfgamaral** [comment] 2019-07-12 10:24
If having `99designs/keyring` as a dependency doesn't cause any problems I think we should keep it because it provides multiple secure credential stores and LevelDB is less secure. I wouldn't make that trade.

I guess the only issue here is that none of the current credential stores are headless friendly, but maybe we could add an option to work around it? Here's what I propose:

With `SecretsBackendType` set to `auto` (the default) this will actually pick `file` for headless systems (like Docker). The only problem with this store is that it keeps prompting the user for a password (not headless friendly):

https://github.com/nmrshll/gphotos-uploader-cli/blob/7850870eae1178a013811be4f5c82e27e50bf281/datastore/tokenstore/repository_keyring.go#L56

https://github.com/nmrshll/gphotos-uploader-cli/blob/7850870eae1178a013811be4f5c82e27e50bf281/datastore/tokenstore/repository_keyring.go#L114-L122

But I worked around this on my Docker image with this simple change: https://github.com/rfgamaral/gphotos-uploader-cli/commit/0158c317f7d07098027408bcd9183f619216438f

Maybe we could add some kind of option to `gphotos-uploader-cli` to disable the password function prompt (like I did above) for `SecretsBackendType: file` (or when `auto` picks `file`)?

**Comment by pacoorozco** [comment] 2019-07-12 10:32
@rfgamaral but in this case your are not suppliying any password to encrypt `file`. So the file is plain-text (like LevelDB approach). Wouldn't it be the same if you provide this password as a parameter to `gphotos-upload-cli`? 

I mean adding a new configuration field `SecretsBackendKey` that could be used in case of `file` is selected as backend. WDYT?

**Comment by rfgamaral** [comment] 2019-07-12 10:46
> @rfgamaral but in this case your are not suppliying any password to encrypt `file`.

I'm actually supplying an empty password (i.e., `""`), if that encrypts `file` or not, I'm not sure.

> I mean adding a new configuration field `SecretsBackendKey` that could be used in case of `file` is selected as backend. WDYT?

You could do that, yes, but what would be the point really? I mean, the password is there, in the configuration file, as plain text, visible to anyone. That or an hard-coded password (empty string or something else) is practically the same thing in terms of security.

It doesn't really matter how we supply the password to the prompt function, **if we don't prompt the user to type the password every time**, we are making it less secure by design.

But let me make you a different question...

For headless systems, like Docker, is it really that import to encrypt the authorization token? I mean, when you log into your account on your browser, a token is also stored on your browser, AFAIK, this is not encrypted (it's usually a cookie). Anyone with physical access to your browser will be able to get your token, it's right there. There's not much difference when using this in a headless server or a Docker container IMO.

**Comment by tonymet** [comment] 2019-07-13 23:43
I found testing for keystore at runtime to be pretty easy -- imo i would test for the keystore by platform ( linux = gnome keyring, apple = keychain, windows = ??), and then fallback to leveldb by default (since leveldb is a build dep). 

If you like the approach i can code it up, i did something similar for another PR

**Comment by pacoorozco** [comment] 2019-07-14 17:31
I'm still a bit concerned about storing the oAuth access token in plain text. Once you have this token you can do all the actions you like until it is expired. If we keep refresh token in the same way, we should do it, this mean that the time that a third person could use it is bigger. **So I'm not sure about keeping the token in plain text.**

It's not the safest approach, but in order to discourage this I would like to add a parameter to supply the encryption key for `file` backend. Then in headless / docker you can supply this key in runtime. If someone steal the image, this would have the token in an encrypted form. 

Obviously, if someone have access to the running docker, he/she can get the encryption key. But IMO this is better than storing the token in plain...

@tonymet @rfgamaral What do you think?

**Comment by rfgamaral** [comment] 2019-07-14 20:04
I might be wrong but in this particular case - in general, nothing sensitive as an access token should be stored as plaintext - I honestly don't think it makes a whole lot of difference.

It doesn't matter if the token is plain text or encrypted. If someone has access to your Docker container (not image), they also have access to the encryption key and can decrypt the access token. I can't see a way for you to supply the encryption key **without user interaction**, and that's the important bit for a true headless implementation. In the end, you're just making it slightly harder for someone to have access to the access token, which is pointless against someone determined to get it.

And if someone has access to the Docker container, you have much bigger problems than worrying about an access token to your Google Photos.

<hr>

I still think that what I said above is somewhat important and relevant but I just thought of something else when I finished writing that post.

>Then in headless / docker you can supply this key in runtime.

Supplying the encryption key in run time is kinda pointless IMO (reasons on post above). But what we could do is supply the encryption key in **build time**, hidden from everyone. How could we do this? One possible solution:

1. Change `terminalPrompt` to read a specific environment variable, the encryption key (make it random, long, and hard to guess).
2. Add that environment variable to the CI build server.
3. Only the CI build server (and people with access) would know how to decrypt the access token.

As for my Docker image - since I have build my own binaries anyway - I'd just have to supply my own encryption key to that environment variable. Only I, my Docker build server (and people with access) would know how to decrypt the access token.

This would put the trust of the access token on the users compiling the binaries instead of the users simply running the binaries. If you put the trust on the users running the binaries you'd have the same problem as mentioned above, access to encrypted file would probably mean access to the machine, thus bigger problems, thus encrypted or plain text would be irrelevant.

What do you think?

**Comment by rfgamaral** [comment] 2019-07-23 15:31
@pacoorozco I just made this change for my Docker image: https://github.com/rfgamaral/gphotos-uploader-cli/commit/4dd58168547b05b2dea5d59c09c652c74749903b

**Comment by pacoorozco** [comment] 2019-07-23 15:41
I like this approach @rfgamaral ! What do you think if I add a `--headless` flag? If it's set the `SecretsBackendType` is set to `file` and the `terminalPrompt` is set to your implementation.

I think this approach has the best of the two worlds :-D *How do it sounds to you?*

**Comment by rfgamaral** [comment] 2019-07-23 16:45
@pacoorozco How exactly would that flag be used? In run time or build time? Can you provide an example?

**Comment by pacoorozco** [comment] 2019-07-23 18:04
I was thinking to use the flag on run time. 
```
$ KEYRING_ENCRYPTION_KEY=verySecretKey; ghotos-uploader-cli --headless
```
or, in your case:
```
$ docker run -r KEYRING_ENCRYPTION_KEY=verySecretKey gphotos-docker
```

**Note:** This not solve that users on host/docker would be able to see this encryption time, as far as they can access it, but it will be the only ones affected. In case you use a proper docker service you can encrypt this var using [secrets](https://docs.docker.com/engine/swarm/secrets/). 

So in unsafe environments, you are probably going to use it.

**Comment by rfgamaral** [comment] 2019-07-23 19:49
Personally I'm not really fond of that... You're forcing the users to always pass those extra options to the CLI, making everything more complex and harder to mantain. IMO, we should explorer other options.

P.S.: I wanted to write a few more things (I have a different suggestion but it would be at build time) but I'm on my phone and don't have much time now.

**Comment by rfgamaral** [comment] 2019-07-23 19:53
The idea of an headless mode is to fully automate the process and if you do it that way, you'll have the encryption key as plain text somewhere (for instance a cron job - not everyone uses Docker).

**Comment by pacoorozco** [comment] 2019-07-23 21:51
Yes, you're right, but I think this approach is safer than using a fixed key or define it in build time, not everybode knows/wants to build the CLI. 

So, using this CLI in headless mode is NOT safe, but If someone wants to use it, he/she can do it.

**Comment by rfgamaral** [comment] 2019-07-24 00:15
> Yes, you're right, but I think this approach is safer than using a fixed key or define it in build time(...)

At build time, only a limited number of people will know the key. At run time, you have no way to control that. If you want to use this tool for automated uploads, the key will be in plain text. If you don't automate but run the command like that in the shell, the key will be stored in the shell history. **This is not safer than using a fixed key that practically almost no one knows.**

> (...)not everybode knows/wants to build the CLI.

No, they don't, but they don't need to if you bake this into the official binaries with a key that only the build server knows about it (and of course, people with access, which should be very limited anyways).

> So, using this CLI in headless mode is NOT safe, but If someone wants to use it, he/she can do it.

So what's the point really? Why make the tool more complex and more confusing to use for no good reason!?

<hr>

The goal should be to make a simple tool for everyone to use easily without worrying to much about it, but the way I see it, you're doing the opposite. I'm starting to realize we don't see eye to eye. I'm sorry, but I really don't think this is the right direction and I'm going to redirect my efforts in providing a good user experience for my Docker image users based on my fork of `gphotos-uploader-cli`.

**Comment by pacoorozco** [comment] 2019-07-24 06:52
I can't agree:
> At build time, only a limited number of people will know the key. 

People are not intended to build its own CLI. They want to install it using snap, brew or binaries. So doing it in build time it doesn't seem an option.

> At run time, you have no way to control that. If you want to use this tool for automated uploads, the key will be in plain text. If you don't automate but run the command like that in the shell, the key will be stored in the shell history. This is not safer than using a fixed key that practically almost no one knows.

You should run it in a safe environment. I don't recommend to run this (with `--headless` flag) in a shared computer. So, you are limiting the circle of trust to the people that has root access to the host running the CLI. Otherwise, they are not able to see your process parameters or environment variables.

There are ways to avoid the the key goes to shell history (e.g. supplying it inside the config file). The same approach is followed by [mysql docker](https://hub.docker.com/_/mysql). IMO if this shell history is only accessible by me, I don't care about it, because I'm delegating security to the fact that they need to access to my account.

> No, they don't, but they don't need to if you bake this into the official binaries with a key that only the build server knows about it (and of course, people with access, which should be very limited anyways).

I'd know the key of everyone. I don't want to have this responsibility. This is open source, so all code should be open... I'm sorry, but I don't think that people are going to be fine if we encrypt a file that they doesn't know how to decrypt. Let's imagine that the key was leaked, how can we replace all of them?

It's better that we delegate this to the users. Users cn supply its own key, they are responsible of ensuring it is not leaked.

> The goal should be to make a simple tool for everyone to use easily without worrying to much about it, but the way I see it, you're doing the opposite. 

Headless is one of the use cases that we are trying to cover. And we've been working to bring `gphotos-uploader-cli` closer to headless use case (see #71 and this thread). When you are familiar with docker, you are used to put environment varaibles with your secrets (or mounting it as volumes) like everybody is doing with [mysql docker](https://hub.docker.com/_/mysql) or [postgres docker](https://hub.docker.com/_/postgres).

There is [another approach](https://medium.com/@basi/docker-environment-variables-expanded-from-secrets-8fa70617b3bc) that we've not tested. Using `secrets` seems you can share sensitive data without exposing it. But this is under docker development scope (aka you :-D)

**Comment by rfgamaral** [comment] 2019-07-24 10:22
The thing you are failing to understand is that everything you proposed is completely pointless and doesn't provide any security at all.

The current implementation prompts the user for a password every time it needs one to encrypt/decrypt the token. **This is the safest you can get and you're placing the responsibility entirely in the user.** If you don't want to have any responsibility at all, you might as well close this issue and don't change anything.

Everything else you proposed **stores the encryption key in plain text**, in one way or another and that is something that goes against something you initially said:

> I'm still a bit concerned about storing the oAuth access token in plain text.

Now, the point of this issue was to make this tool more headless friendly and the point of an headless mode is automation. **If you implement something that requires you to pass the encryption key as a parameter, you'll be storing the encryption key as plain text somewhere.** This doesn't solve anything.

> There is another approach that we've not tested. Using secrets seems you can share sensitive data without exposing it. But this is under docker development scope (aka you :-D)

That only works with Docker swarms, it's not an option for my Docker image.

<hr>

Honestly, I think this discussion is becoming longer than it needs to be and you're creating a problem that doesn't exist. IMO you are too worried about security when there's nothing to worry about, which is something I've tried to explain from the very beginning.

People are most likely using `gphotos-uploader-cli` to upload their personal photos to Google Photos from their own personal computers or their own NAS. These are most likely local machines, stored on people's homes. **The only way for the token to be leaked/compromised is if people are hacked or someone gains physical access to their machines.** Otherwise your token is safe, encrypted or not.

If you are hacked or if someone that shouldn't has physical access to your machine, **you have much bigger problems to worry about than an access token being leaked**, especially when that token only has access to the Google Photos API.

In other words, if someone is able to access my Docker container and read the access token, they can also access my browser and read all my cookies (thus accessing all the access tokens for my logged in accounts). What do I think I should be more worried about? The tokens or that someone that shouldn't gained access to my computer?

<hr>

One last thing, I'm going to revert https://github.com/rfgamaral/gphotos-uploader-cli/commit/4dd58168547b05b2dea5d59c09c652c74749903b. It was a pointless change because the value of the environment variable was never stored in the compiled binary and the default was an empty string (basically the same thing that was before).

In a way, I could add instructions to my users to set that environment variable to the Docker container and let them encrypt the access token with their own encryption key, placing the responsibility completely on them, just like you wanted. However, it's pointless, because the encryption key will still be stored in plain text right there on the host machine, it doesn't provide any security at all.

The way I see it, we still haven't found the best solution for this problem. Well, kinda, cause I don't really think this is a problem at all ¯\_(ツ)_/¯

**Comment by pdecat** [comment] 2019-07-28 10:53
Please leave `gnome-keyring` as an option to store the token.

PS: by the way, thanks to all contributors here!

**Comment by carlolars** [comment] 2019-08-06 15:59
[Rclone](https://rclone.org/) for example stores the token in plain text, just set the file permissions on that file to prevent other users to read it.

If a system has been compromised it means that the attacker has root access, and if so a password entered by the user, which can be sniffed, is not much safer than file permissions.

**Closed** 2019-10-05 22:33 UTC
Labels: help wanted, question
