### ISSUE TITLE
Docker: token expired and refresh token is not set

### ISSUE THREAD

**Issue by rfgamaral** [gphotosuploader/gphotos-uploader-cli#130] opened 2019-09-16 19:58 UTC
I'm trying to get my Docker image working with the latest version and after working on a workaround to the whole headless server thing I stumbled upon this issue:

```
2019/09/16 19:18:03 Token has been expired, refreshing
2019/09/16 19:18:03 could not refresh the token: oauth2: token expired and refresh token is not set
```

This only happens with my workaround, the normal implementation/instructions are working just fine. However, to debug this I'd need to have proper GoLang skills and be able to debug the code and inspect variables and network requests, which I don't have. Any chance you could help me figuring out if there's a solution for this @pacoorozco ?

I believe that to be able to get the same beavhior (without using my Docker image) you'd have to use Google OAuth credentials with the "Web application" type of credentials instead of "Other" and test the refresh token mechanism with those, you should get the error above.

All it's left it's to debug the network requests and see if the refresh token can be obtained in a different fashion for this type of OAuth client.

**Comment by pacoorozco** [comment] 2019-09-18 06:16
Hi @rfgamaral 

As far as I understood, the problem is in *your implementation*, right? Because it's working very well in the current `gphotos-uploader-cli` implementation. 

I guess that the problem is that **you are not asking for a Refresh Token** using the *"Web application"* type. In that case you must supply a query param, named `access_type`. [See Google's documentation](https://developers.google.com/identity/protocols/OAuth2WebServer). I'm not sure if your current implementation is doing it right, because for *"Other"* you don't need to set this parameter.

We should review your code in order to set this parameter... Let me review it in your fork.
If I've understood right, please close this ticket and create a new one in your `docker` repo :-D

**Closed** 2019-09-20 17:41 UTC
Labels: question
