### ISSUE TITLE
Select a specific folder to upload

### ISSUE THREAD

**Issue by rparadinha** [gphotosuploader/gphotos-uploader-cli#175] opened 2020-01-08 22:07 UTC
**Is your feature request related to a problem? Please describe.**
I intend to upload all my photos to Google Photos (more than 800 folders) but I would like to upload folder by folder. The reason is Google Photos does not keep the original date from some videos, so I would like at the end of upload edit the date for these videos before moving to another folder. 

**Describe the solution you'd like**
Implement an option (e.g `-f <folder>`) do specify directory folder.

**Describe alternatives you've considered**
It's possible to define source folder using the `sourceFolder` in a new config file using `--config /my/config/dir` but it always requires to edit the config file.

**Additional context**
N/A

**Comment by pacoorozco** [comment] 2020-01-21 07:56
Question: If we provide a flag to specify the folder... what it will happen with the rest of the configuration. Bear in mind that configuration is folder specific, so it would be a mismatch between what you supplied with flags and what you wrote in config file.

I think we should have a way to configure everything by flags, but this will be a very complicated way of configure, given that we need a lot of flags.

**What do you think?**

**Comment by henry54809** [comment] 2020-01-22 16:16
Usually the command line options supersedes everything in the config. In your code you can perhaps take the command line folder options, make them into a json, merge that json with config json to generate the config to be used.

**Comment by rparadinha** [comment] 2020-01-22 20:01
> Question: If we provide a flag to specify the folder... what it will happen with the rest of the configuration. Bear in mind that configuration is folder specific, so it would be a mismatch between what you supplied with flags and what you wrote in config file.
> 
> I think we should have a way to configure everything by flags, but this will be a very complicated way of configure, given that we need a lot of flags.
> 
> **What do you think?**



> Question: If we provide a flag to specify the folder... what it will happen with the rest of the configuration. Bear in mind that configuration is folder specific, so it would be a mismatch between what you supplied with flags and what you wrote in config file.
> 
> I think we should have a way to configure everything by flags, but this will be a very complicated way of configure, given that we need a lot of flags.
> 
> **What do you think?**

It can overrride the `sourceFolder` option for example. 
The way I'm doing now is create a temp folder where I define as a `sourceFolder` and copy the only the directory/s I want to upload.

**Comment by eGit** [comment] 2020-03-19 12:21
It would really help to have just ONE flag: -f sourceFolder

This overwrites the folder defined in config.hjson

**Comment by pacoorozco** [comment] 2020-03-19 13:29
Yes, I partially agree, the problem is that on `config.hjson` more than one folder could be used. So, in case of using `-f` flag which configuration we want to use? First one?

**Comment by eGit** [comment] 2020-03-19 14:31
I am not sure I understand what you mean.

On the console I write:

gphotos-uploader-cli -f /home/me/misc/vacation-videos
gphotos-uploader-cli -f /mnt/data/2016/videos
gphotos-uploader-cli -f /media/old/mix/collection

What I expect it to do is ignore whatever folders are specified in config.hjson and just upload the folder I specified on the console

I use many other CLI tools and that is how they handle things like this. You have a common config file but you can always specify the folder the tool is acting on.

**Comment by pacoorozco** [comment] 2020-03-19 16:43
Hi @eGit 

Sorry, let me explain better. Currently in the configuration file you have a lot of context that is needed to upload the pictures:

```
{
  SecretsBackendType: file,
  APIAppCredentials: {
    ClientID:     "XXXXX",
    ClientSecret: "XXXXX",
  }
  jobs: [
    {
      account: XXXXXX
      sourceFolder: ~/folder1
      makeAlbums: {
        enabled: true
        use: folderNames
      }
      deleteAfterUpload: true
      uploadVideos: true
      includePatterns: []
      excludePatterns: [ "*Album1" ]
    },
    {
      account: XXXXXX
      sourceFolder: ~/folder2
      makeAlbums: {
        enabled: true
        use: folderNames
      }
      deleteAfterUpload: false
      uploadVideos: false
      includePatterns: []
      excludePatterns: [ "*Album2" ]
    }
  ]
}
```

Given that confgiuration and the flag `-f ~/folder3`, it's clear that we should upload **only** files that are inside `~/folder3`, but what it's on regards the configuration. 

- Which `excludePatterns` should we use?
- Which `uploadVideos` should we use?
- ...

I don't honestly know what it will be the best way to approach it...

**Comment by eGit** [comment] 2020-03-19 17:47
Everybody has a different taste. But my opinion on a -f flag is, that it is a 'quick and easy' way to upload a folder. For EVERYTHING else I would recommend using config.hjson

So -f is when I quickly want to upload a folder as an album. It should ignore ALL **jobs** in config.hson. It should just upload the files in the specified folder and create an album with the name of the folder.

Also -f doesn't support patterns or anything else. It is a 'quick and dirty' solution. You can describe what it does in the --help output (it will ignore all settings in config.json except the credentials). 

For everything more complicated you have to use the config.hjson.


Example: gphotos-uploader-cli -f /home/me/misc/vacation-videos

will ignore config.hjson completly. It will create an album 'vacation-videos' and upload all files in the /home/me/misc/vacation-videos to that album.

**Comment by pacoorozco** [comment] 2020-03-19 18:21
Hi @eGit 

It's a good approach but I don't know if it's complete:
- What about folders inside `/home/me/misc/vacation-videos`? Should they be uploaded? Using always `folderNames`?

I don't know... I have doubts about being too specific :sweat: 

Let's see if someone more can help us to decide it

**Comment by eGit** [comment] 2020-03-19 18:24
1. The simplest approach is always the best I think. Ignore subfolders. Just upload the files in the folder and nothing else.

2. Alternatively you could create an album for each subfolder if it contains uploadable files. This complicates things but it is a valid approach.


Again, I would go with the simplest approach. -f is the 'quick and easy' solution to upload all files in a folder. Ignore subfolders.

**Comment by ikwyl6** [comment] 2020-04-11 22:29
Having a nested json file for each individual folder/dir complicates things.. by the time you write it all out, you could have a loop created to run this script over each folder.. If you have all options on the command line, a simple loop in bash can do all your folders and you create an array in bash each folder and it's options and it will loop through.. having a huge nested config file should only be for high-level options for the program itself.. just my input..

**Comment by eGit** [comment] 2020-04-11 22:39
> Having a nested json file for each individual folder/dir complicates things.. by the time you write it all out, you could have a loop created to run this script over each folder.. If you have all options on the command line, a simple loop in bash can do all your folders and you create an array in bash each folder and it's options and it will loop through.. having a huge nested config file should only be for high-level options for the program itself.. just my input..

Nobody is talking about a nested json file for each individual folder. Where do you get this idea?

I don't think I get what you say in the rest of your comment but let me just tell you as somebody who regularly uses Linux/bash: I would prefer not using bash with gphotos-uploader-cli. OSX users would agree even more.

Again: I am not sure your input has anything to do with our discussion.

**Comment by ikwyl6** [comment] 2020-04-12 18:17
Yes you’re correct. I think I was taking everyone’s comments as that the json conf file was not needed when you specify command line arguments.

**Comment by alimanfoo** [comment] 2020-07-19 23:08
Hi, just to say that I also looked for this functionality too initially. However, now I am using the ``includePatterns`` option within the config file to select sub-folders, which I'm happy with, e.g.:

```
{
  SecretsBackendType: auto,
  APIAppCredentials: {
    ClientID:     "***",
    ClientSecret: "***",
  }
  jobs: [
    {
      account: ***
      sourceFolder: /local/path/to/photos/2020/
      makeAlbums: {
        enabled: true
        use: folderPath
      }
      deleteAfterUpload: false
      uploadVideos: false
      includePatterns: [
          "20200705_SD80/**",
          "20200713_NIKON_D40/**"
      ]
      excludePatterns: []
    }
  ]
}
```

**Comment by pacoorozco** [comment] 2020-09-15 07:29
Please, can you take a look to #231 ?

**Comment by pacoorozco** [comment] 2020-09-23 17:54
As @alimanfoo mentioned, this feature could be easily covered using `includePatterns` and `excludePatterns`. 

So I'm going to close this FR and mark it as done!

**Closed by pacoorozco** 2020-09-23 17:54 UTC
Labels: feature request, feedback required, help wanted
