### ISSUE TITLE
Upload in batches by directory to reduce time to start uploading

### ISSUE THREAD

**Issue by wasserman** [gphotosuploader/gphotos-uploader-cli#333] opened 2022-07-01 01:49 UTC
**Is your feature request related to a problem? Please describe.**
First time user.  Trying to upload a photo archive I downloaded from another service I was using.   There's close to 40k files and the tool appeared to be hanging.  I tried it with the `--debug` flag and saw upload messages scrolling fast on the screen.  This was suspiciously fast and I saw no evidence of these albums being created or photos appearing in my Google Photos account.
I then suspected that this was just a queueing phase after testing with a smaller subdirectory.   My full directory tree ended up taking close to 5 minutes until the debug messages completed and the uploads actually started.

The debug message is misleading.  It would be great to know this is just a stage before the actual upload occurs and possibly have some progress of the file harvesting process reported.

**Describe the solution you'd like**
- Progress of file harvesting stage.
- Do batches per folder.  I didn't look at the code, but globbing per folder could help to have negligible pauses between directories and would shorten the wait for the actual uploading stage.
  * I understand that multiple workers could complicate this since a parent process would need to do the harvesting and then passing the job to a worker instead of distributing it across the complete file set.

**Describe alternatives you've considered**
No alternatives, just sharing my thoughts from my initial experience.  This project is almost exactly what I would have imagined.  Great instructions on setting up the API keys and it appears to be a solid solution.  Thanks!  

**Additional context**
n/a

**Comment by patrikja** [comment] 2023-05-23 13:44
I want to support this feature request, which for me actually turns into a bug. 
The problem is that I'm trying to upload a collection of around 500 directories with more than 50k files, but after the first 10k API requests Google throws an error for every subsequent request that day.
I first thought this would just mean I could restart the following day, but then the first 10k requests are used up even before uploading anything, just to get the tool to realize that all the first X files are already uploaded.
Thus, it seems I will need to "hand-batch" to get this to work.
Suggestions for how to do that (configuration-wise) or where to look for the part of the code I could modify would be welcome.
Kind regards,
  Patrik
PS. I have no direct Go experience, but I have done quite a bit of programming in other languages, and teach programming at university level.

**Comment by pacoorozco** [comment] 2023-05-24 14:24
Hi Patrik

The behavior you're experimenting is not the expected one. The CLI should scan, get the files to be uploaded, remove the ones were already uploaded and build a list of files per album name without sending any request to Google Photos API. 

After that phase, [it should create the album (if it doesn't exists) and upload the files](https://github.com/gphotosuploader/gphotos-uploader-cli/blob/cb3889f764854fe122c81d5bd032d0babc969045/internal/cmd/push.go#L114).

As far as I understood, you are consuming the Google Photos quota before uploading anything, does it? 

**Can you review the Google Dashboard to see which kind of requests are consuming your quota?**

**Comment by patrikja** [comment] 2023-05-25 15:29
Well, then I suggest creating one album at a time, just before uploading files into it. In this way, it should be possible to get good progress even with many directories/albums.
Would that be reasonably easy to fix?
/P

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by patrikja** [comment] 2023-06-06 09:08
OK - I have now worked around this problem for two weeks by first adding a long "exclude" list of all top level directories and then removing one at a time when the previous batch was done. This sort of works but is inconvenient. 
I have now reached a single top level directory with around 25k files in many subdirectories. Yesterday's run used up around 9k API requests for "ListAlbums", around 50 for "CreateAlbum" and only the remaining around 1k for BatchCreateMediaItems. Thus around 24k files still remain and I was hoping today's new run would focus entirely on the files. Unfortunately the first 15min today has spent 2k API calls on "ListAlbums" and only 11 on uploading files.
Thus it looks likely that also today few calls will remain for actual uploads. 
My guess is that a similar book-keepinging as what is used to avoid multiple uploads of files also needs to be in place to avoid multiple ListAlbums calls. [But I don't really know the API, so I'm just guessing.]
There is one difference from yesterday - today no new CreateAlbum calls have been made yet - so perhaps this indicates a better run may still be possible.
But if the same situation as yesterday is repeated only 1k files will be uploaded, meaning that the remaining 24k files in this directory will take 24 days! (and the remaining 10 directories the rest of the year ...)
Any suggestions welcome.

**Comment by patrikja** [comment] 2023-06-06 13:27
Just to add some new numbers: today's 10k quota was used up by g-p-u-cli as follows: no albums created, 8373 calls to ListAlbums, 1634 calls BatchCreateMediaItems.


Method
Requests
Errors
Avg latency
99th percentile latency 
google.photos.library.v1.PhotosLibrary.BatchCreateMediaItems	1,634	0.43%	1.812 seconds	6.723 seconds
google.photos.library.v1.PhotosLibrary.ListAlbums	8,373	0	0.33 seconds	0.946 seconds

**Comment by pacoorozco** [comment] 2023-06-06 14:11
Thanks a lot for this data... It's extremely useful... 🙇🏼 

Let me try to explain (when possible) why this is happening:

**Google Photos only allows ~10K requests per day**

The CLI scan your folders and build a list of files to be uploaded:

```// get UploadItem{} to be uploaded to Google Photos.
		itemsToUpload, err := folder.ScanFolder(cli.Logger)
		if err != nil {
			cli.Logger.Fatalf("Failed to process location '%s': %s", config.SourceFolder, err)
			continue
		}
```

Once it has build this huge list, it group the files by Albums:

```
// Get items to be uploaded by album name, this reduce a lot the calls to Google Photos API to get albums ID.
		itemsByAlbum := make(map[string][]string)
		for _, i := range itemsToUpload {
			itemsByAlbum[i.AlbumName] = append(itemsByAlbum[i.AlbumName], i.Path)
		}
```

And then, it must obtain the Google Photos Album identifier `albumId`:

```
albumId, err := getOrCreateAlbum(ctx, photosService.Albums, albumName)
			if err != nil {
				cli.Logger.Failf("Unable to create album '%s': %s", albumName, err)
				continue
			}
```

Unfortunately, the **Google Photos API doesn't have a call to get this `albumId`**, so we have to list all the Albums in your account until find the right one. In order to reduce the number of calls, there's a cache that stores the album names and the `albumId` for each Album. **The cache is not persistent between calls.** (to ensure its consistency).

After that point, we start to upload the file and after the completion of the upload, to add it to the Album. So you can expect, at least, two requests for each file.

>  Yesterday's run used up around 9k API requests for "ListAlbums", around 50 for "CreateAlbum" and only the remaining around 1k for BatchCreateMediaItems

Based on your data, and **considering that you only run the CLI once**: 

- Either you have a lot of Albums or the internal cache is not working. **Do you know how many albums are present in your Google Photos Account?** (see below)
- Only 50 albums where new.
- With the rest of API calls only 1K files were able to be uploaded.

Currently, after reaching the "quota exceed" status, the CLI exit, loosing the Album's cache... So the next run of the CLI will consume the same amount of API calls than before 😢 

Possible fixes:

1. **Fixing the internal cache**: Unless you have a huge amount of albums (> 1M), it could be that the cache is not working.
2. **Instead of exiting, we can wait 24h and continue uploading**. The Album's cache will be still on memory and ready to upload files. Changes in the filesystem will not be taken into consideration until the next run of the CLI.
3. **Caching the Album's data persistently could help**. It will not be definitive, because if at any time a new folder is added. The CLI will invest the same amount of request to refresh the cache than now, but It's still something to consider.


I hope this have give you better understanding of what's happening... Even that I know it nos fixing anything.

**Comment by patrikja** [comment] 2023-06-06 14:24
There are around 1k albums in the account, at least half of which have been created by g-p-u-cli (probably on the first unrestricted run). Most of them are still empty (waiting for their files...).
The "wait 24h and continue" feature would be great - that would solve both the caching and the "manual restart". (But restarting at 00:01 the next "google day", not 24h after the failing call.) That would get around 5-10k images uploaded each day for the next few weeks (or at least for one week due to the need for renewed authentication).
Alternatively, a flag to enable using the previous album name cache. (--unsafe-use-album-cache or something like that)
Kind regards,
  Patrik

**Comment by pacoorozco** [comment] 2023-06-07 07:57
I'm thinking to fix it in that way:

1. Build a Album's cache at the beginning: listing all the albums when the CLI starts (1K albums should require ~20 reqs)
2. Each new album will be created and cached (1 reqs per each new album)
3. Start the uploading phase + media creation (2 reqs per each file)

If quota is exceeded the CLI will wait until next day (kind of) until the new quota is available.

I'm not going to implement the persistent Album's cache (yet), because it will add a lot of complexity and getting the Album's list should not be so expensive (I hope).

Thanks for helping me to design future changes

**Comment by patrikja** [comment] 2023-06-07 13:36
Sounds good. Can I be of help?

**Comment by pacoorozco** [comment] 2023-06-07 15:30
Hi @patrikja 

Of course you can help... 

I've started the development in the `issue-333` branch. Feel free to help with the code if you want, or if you prefer you can help me to review the PRs.

Until now, I've finished a quick release to test if the approach could help. **Do you mind to test [this release](https://github.com/gphotosuploader/gphotos-uploader-cli/releases/tag/v4.0.0-alpha-01)?**

It should reduce the amount of requests to get the Album's list (keep an eye on the `google.photos.library.v1.PhotosLibrary.ListAlbums` number of requests) and it should wait 12h after daily quota is expired... 

Any feedback is more than welcomed! 🥺

**Comment by pacoorozco** [comment] 2023-06-07 15:47
Hi @patrikja

Of course you can help...

I've started the development in the issue-333 branch. Feel free to help with the code if you want, or if you prefer you can help me to review the PRs.

Until now, I've finished a quick release to test if the approach could help. Do you mind to test this release?

It should reduce the amount of requests to get the Album's list (keep an eye on the google.photos.library.v1.PhotosLibrary.ListAlbums number of requests) and it should wait 12h after daily quota is expired...

Any feedback is more than welcomed! pleading_face

**Comment by patrikja** [comment] 2023-06-10 21:00
Thanks for the rapid response and sorry for the delay, I only now had time to get back to this.
* I downloaded and installed https://github.com/gphotosuploader/gphotos-uploader-cli/releases/tag/v4.0.0-alpha-01 
* I started it at 22:35 with ./gphotos-uploader-cli --debug push
* Seems to work (it started working on the 21578 files left in current directory)
* After 5min: 23 ListAlbums, 79 BatchCreateMediaItems - seems promising
* After 20min: still just 23 ListAlbums (good), now 332 BatchCreateMediaItems (yes!)

Thus it seems to be a great improvement - thanks!

I can add another comment when the 10k quota runs out.
(and if it works as intended, I may be able to remove my "exclude" list and run it on the full image repository).

## Parts of the log
...
[info]   Found 21578 items to be uploaded processing location '/home/ragu/Bilder'.
[debug]  Processing (1/21578): /home/ragu/Bilder/2013/AnonymizedDirName/2013_0330_103726AA.jpg
[debug]  New resumable upload for file [2013_0330_103726AA.jpg].
[debug]  Current offset for [2013_0330_103726AA.jpg] is 0.
[debug]  Resuming upload session for [2013_0330_103726AA.jpg] starting at offset 0
[debug]  Processing (2/21578): /home/ragu/Bilder/2013/AnonymizedDirName/2013_0330_104322AA.jpg
[debug]  New resumable upload for file [2013_0330_104322AA.jpg].
[debug]  Current offset for [2013_0330_104322AA.jpg] is 0.

**Comment by patrikja** [comment] 2023-06-11 13:56
I can report that it worked as intended: the 10k requests only used those 23 ListAlbums calls and ~9950 file uplaods. Great. Instead of waiting 12h for it to continue I will now restart it without all my "exclude" directories to stress test it with _many_ files and directories.

**Comment by pacoorozco** [comment] 2023-06-11 14:10
Hi @patrikja 

First of all, thanks for the tests and the results you are sharing. 

I'm glad to see that the new approach works better than de old one in terms of API calls to list the albums. 🤩

I'm still working on improving the daily quota management. I'm going to release a new version,  next week, reducing the number of requests when uploading, I'm going to restrict resumable uploads only for big files. 

I'm estimating that the current code has used 9950 API calls to upload around 3K files.  Would you able to confirm it?

**Comment by patrikja** [comment] 2023-06-11 14:18
It seems to be better than that - at least the last log message was about processing file 9954/21578 just before getting the quota exceeded error. And earlier days the number of the last attempted file was within 30 of the actual files uploaded. 

In any case, I have started the "big" run - for the rest of the repository. 

patrikj> ./gphotos-uploader-cli --debug push

[debug]  Current configuration: *Censored*
[info]   Authenticating using token for *Censored*
[done] √ Token is valid, expires at 2023-06-11 17:00:28.043910606 +0200 CEST m=+3599.424864954
[info]   [DEV] This is a development version. Please be warned that it's not ready for production
[info]   Found & cached 1129 albums.

...

[info]   Found 137395 items to be uploaded processing location '/home/ragu/Bilder'.
[debug]  Processing (1/137395): /home/ragu/Bilder/2013/2013_11_21_Lanzarote_1/2013_1031_130227AA.jpg
[debug]  New resumable upload for file [2013_1031_130227AA.jpg].
[debug]  Current offset for [2013_1031_130227AA.jpg] is 0.
[debug]  Resuming upload session for [2013_1031_130227AA.jpg] starting at offset 0

+ First five minutes: around 100 file uploads started, only 23 ListAlbums.

**Comment by pacoorozco** [comment] 2023-06-11 16:55
I have doubts about these 100 file uploads... 

- I'm sure that the minimum number of request for a file is 2 (one for upload and one to add it to the album). 
- Using resumable uploads the minimum number is 4 (one for starting the upload, one for uploading, one for finishing the upload and one to add it to the album)

But based on your stats (and my tests) it seems that 'upload' requests doesn't call for the quota (the request to add it to the album counts).

Maybe you can confirm it watching the number of uploaded files and the number of requests consumed.

**Comment by wasserman** [comment] 2023-06-11 19:02
Please note that #335 was relevant to the 10k, so I just am mentioning it so it wall be referenced.  In my scenario I ended up just spending time doing it manually through the Photos Web UI.  It was a great excuse to skim through 20 years of photos.  

Thank you @patrikja and @pacoorozco for making progress on this issue.

**Comment by patrikja** [comment] 2023-06-11 19:52
OK, I did an experiment: first, the file number in the log increases
in sync with the API count (with an error less than 1%). So it seems
like the program is trying to upload one file for each request. Still
after 5000 files and as many API requests they are within 5. 

Second, the actual images appearing at google photos come at also come
at almost that rate but it is a bit harder to measure accurately: the
"recently uploaded" (as checked by reloading
https://photos.google.com/u/1/search/_tra_) seems to come with an
uneven delay - probably some batch processing later in the google
photos pipeline. Mostly the images/videos appear slowly (a few second
apart) but then sometimes a hundred or so come at once.

I had ~633 files appearing while the file number in the log increased
by 1000. Thus the ratio was 1.58 which is a bit odd. The accuracy is
quite low, due the "batching" so I should perhaps say ratio = 1.5+-0.3.

**Comment by patrikja** [comment] 2023-06-12 13:51
Possibly a new issue: after the 12h wait, uploading resumed and after around an hour g-p-u-cli started creating many albums of the same name, with one file in each. I stopped it after around 450 "singleton albums" were created. Perhaps related to the album ids?

I have now restarted it, in the hope it would not continue the "one file per album" business. But it does - I stopped it again after around 150 "singleton copies" of the next album in line.

I'm not sure how to help debugging it, but I would suggest making more things visible in the log printed by --debug (or adding different log levels). Currently the --debug log does not seem to say anything about albums.

**Comment by pacoorozco** [comment] 2023-06-12 17:55
I see the problem... it's a bug 😓 

Let me fix it and release a new version... apologies... the previous version was not tested enough...

**Comment by pacoorozco** [comment] 2023-06-13 11:00
Hi @patrikja 

I've just released a [new version](https://github.com/gphotosuploader/gphotos-uploader-cli/releases/tag/v4.0.0-alpha-02) fixing the problems you were experimenting.

In the previous version, when a new album was created after the `albumsCache`, it was not added, that's why it was creating & re-creating it over an over. I've used a proper cache to add created albums to the `albumsCache`.

I've added some more debug messages... **Let me know how it works** and thanks a lot for your patience.

**Comment by patrikja** [comment] 2023-06-13 12:10
I have now installed the https://github.com/gphotosuploader/gphotos-uploader-cli/releases/tag/v4.0.0-alpha-02 new version and it seems to work well. First ~330 requests were 34 ListAlbums and around 300 regular uploads (+1 new album created). I also saw ~300 images appear during that same time, so currently the image/API calls ratio is 1 - very nice!

A detail is that the early log message for the previous test release said
  [info]   Found & cached 1129 albums.
while this second test release said
  [info]   Found & cached 1033 albums.
which is a bit surprising given that the first test release created around 600 (singleton) albums and no albums were removed in the meantime.

Perhaps the number is now measuring the number of unique album _names_ instead of unique album _IDs_?

**Comment by pacoorozco** [comment] 2023-06-13 17:48
You're right @patrikja 🎩 

I did not think about it, but Google Photos allow several albums with the same name [1129 albums], then the `albumsCache` is created using album's name as key, so only unique albums are cached [1033 albums]. This explains the difference.

If you ask me, I think it's more correct in this way... **WDYT?**

And thanks a lot for your invaluable help testing the early releases 👏🏼

**Comment by patrikja** [comment] 2023-06-15 10:00
Reporting the number of unique album names is fine. (A separate feature request would be to support "merging" albums with the same name but I realise this is quite different from the main purpose of the tool.)

About the 12h delay: yesterday the run ended more than 12h before the end of the "google day", thus the next attempt would also have failed, thus delaying another 12h (which would have been 11h later than necessary). Instead I manually stopped it and restarted it in the morning. 
It would be great if the 10k-API-full delay would be until the new google day starts instead. Perhaps not starting the exact minute of the new day, but within an hour.

In any case, the uploader now works well enough for me to just "forget about it" for the next two weeks until it has uploaded the remaining 125k images.
Thanks for a nice tool!

**Comment by pacoorozco** [comment] 2023-06-15 10:58
Ohhh... I'm very glad to read that it's working fine!

I'm going to release the new version (with some breaking changes) soon, where I would close this issue too...

One more time, thanks a lot for being an excellent testers... your feedback was key to follow up with the issue. 🙇🏼

**Comment by patrikja** [comment] 2023-06-25 21:21
Just to report back - it has now finished uploading the remaining 125k files (mostly images, 5% movies).
When it finished it had a handful och "failed uploads" which were all but one uploaded on a second identical run (which only uploaded those remaining).
/ P
PS. One file was 0 bytes on disk - probably from a bad download from a camera at some point - and it gave an error message from the API. I just deleted it.

**Comment by pacoorozco** [comment] 2023-06-26 06:04
Thanks @patrikja 

I'm almost finishing the next release which will include the fix that you've tried... 👏🏼

**Closed** 2023-10-21 08:03 UTC
Labels: enhancement, fixed
